# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("http://localhost:3000/sresult")
    self.driver.set_window_size(1553, 840)
    self.driver.find_element(By.LINK_TEXT, "Collab Buddy").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-search").click()
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").click()
    self.driver.find_element(By.ID, "search").send_keys("Web Dev")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".far").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-search > path").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-outline-light:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Web Dev").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4:nth-child(1) .btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4:nth-child(1) .btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-4:nth-child(1) .btn")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".my-sm-0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-control").send_keys("Web Dev")
    self.driver.find_element(By.CSS_SELECTOR, ".my-sm-0").click()
    self.driver.find_element(By.CSS_SELECTOR, "h3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".icon-bullet").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".far").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) > .text-white").click()
    self.driver.find_element(By.LINK_TEXT, "Student Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".mb-0").click()
  
