# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import time

from selenium import webdriver

driver = webdriver.Chrome(executable_path=r'D:\software\chromedriver.exe')

driver.get("http://localhost:3000/")
driver.find_element(By.LINK_TEXT, "Register").click()
driver.set_window_size(655, 753)
driver.find_element(By.NAME, "email").click()
driver.find_element(By.NAME, "email").send_keys("theinvincible375@gmail.com")
driver.find_element(By.NAME, "password").click()
driver.find_element(By.NAME, "password").send_keys("123456")
driver.find_element(By.NAME, "login").click()
